name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort
      - name: Print date
        run: echo "::set-output name=date::$(date +'%d-$m-%Y')"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
      - name: Print date for 2nd job
        run: echo "::set-output name=date::$(date +'%d-$m-%Y')"
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Print date for third job
        run: echo "::set-output name=date::$(date +'%d-$m-%Y')"
  job4:
    deploy: 
    needs: [job1, job2]
    name: Forth job with dependency
    runs-on: ubuntu-latest
    steps:
      - name: step one
        uses: actions/checkout@v3
      - name: print date for forth job
        run: echo "::set-output name=date::$(date +'%d-$m-%Y')"
